### ISSUE TITLE
[Error / Need Help] Trying to sync two remotes :: UnboundLocalError: local variable 'new_remote' referenced before assignment

### ISSUE THREAD

**Issue by ghost** [endevrr/AutoRclone-Rewrite#5] opened 2021-08-05 21:35 UTC
Hey!
I'm trying to sync two different remotes, one uncrypted on a Gsuite acc, to a encrypted remote on a Team Drive / Shared drive.

My `rclone.conf` is basically like this (removed "secret" info):
```
[gcd-admin]
type = drive
client_id = xxxxxx.apps.googleusercontent.com
client_secret = xxxxxx
token = {xxxxxx}
scope = drive

[gcd-team]
type = drive
client_id = xxxxxx.apps.googleusercontent.com
client_secret = xxxxxx
scope = drive
token = {xxxxxx}
team_drive = xxxxxx
root_folder_id = 

[gcd-crypt]
type = crypt
remote = gcd-team:media
password = xxxxxx
password2 = xxxxxx
```

I really want to sync the `gcd-admin` to `gcd-crypt`, which is a crypt mount that is setup to use the team drive (`gcd-team`).
The `gcd-admin` is in a "regular" (enterprise) Gsuite, and the team drive is on a shared drive. Both are on the same account.

The folder that I'm trying to sync from `gcd-admin` is shared with everyone with the link, and `gcd-team` is shared with the group that has A LOT of service accounts connected to it.

But when I run this command:
`python3 autorclone.py --sync -s gcd-admin: -sp plex/ -d gcd-crypt: -dp plex/ --rclone-config-path /home/appbox/.config/rclone/rclone.conf --drive-chunk-size 64M --transfers 8 --dry-run`

I get this error:
```
axxbxx@XPPX:/opt/AutoRclone-Rewrite$ python3 autorclone.py --sync -s gcd-admin: -sp plex/ -d gcd-crypt: -dp plex/ --rclone-config-path /home/appbox/.config/rclone/rclone.conf --drive-chunk-size 64M --transfers 8 --dry-run

[2021-08-05 17:28:19] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-05 17:28:19] [AutoRClone] (untitled) [INFO] Generating RClone config file...
Traceback (most recent call last):
  File "/opt/AutoRclone-Rewrite/autorclone.py", line 304, in <module>
    main()
  File "/opt/AutoRclone-Rewrite/autorclone.py", line 88, in main
    end_id, src_is_crypt, dst_is_crypt = config_gen.gen_rclone_cfg(args, rclone_generated_config_path)
  File "/opt/AutoRclone-Rewrite/util/config_gen.py", line 101, in gen_rclone_cfg
    parsed_config = config_parser.parse_config(args.rclone_config_path)
  File "/opt/AutoRclone-Rewrite/util/config_parser.py", line 99, in parse_config
    remotes.append(new_remote)
UnboundLocalError: local variable 'new_remote' referenced before assignment

```

Is there any way to solve this, or is this way of sync not possible (from unencrypted to encrypted)?

**Comment by williamjohnstone** [comment] 2021-08-05 22:57
Hello, thanks for the report, 

Good news is this sync is possible, bad news is that this is an issue I have somehow introduced that I never got around to debugging, this is a duplicate of #3 I shall try and get around to solving this but I'm still spread extremely thin, in the meantime you should be able to do this sync manually using rclone, I apologise for the inconvenience.

**Comment by williamjohnstone** [comment] 2021-08-05 23:14
Update: I have decided to tackle this issue now, I have been able to reproduce this issue locally, so should make debugging easier.

**Comment by williamjohnstone** [comment] 2021-08-05 23:29
Ok, this issue occurs when there is a config item with a type of `drive` and it does not contain `team_drive` or `root_folder_id` in your case this is caused by your `gcd-admin` config entry. This is caused by this bit of code here 
```python 
if remote_type == "drive":
    if team_drive or root_folder_id:
        new_remote = drive_remote(name, team_drive, root_folder_id)
    else:
   ---> pass <---
```
I was under the impression that either one of these was required for a valid rclone remote, turns out this is only for shared drives, I never considered personal drives, I shall work on a fix now.

**Comment by williamjohnstone** [comment] 2021-08-05 23:36
So turns out I wasn't being dumb when I wrote that, it isn't possible to use service accounts on a personal drive without first sharing that folder which would provide a root folder id, see [here](https://rclone.org/drive/#root-folder-id), I will add a more descriptive message, but you'll need to follow those steps to be able to sync your remotes, if you require any more help let me know.

**Closed as completed** 2021-08-06 00:03 UTC
Labels: bug

**Comment by ghost** [comment] 2021-08-06 08:20
Hey, thanks for taking a look at it. @endevrr 
I edited my `rclone.conf` - removed the gcd-admin and added one with the correct root_folder_id. Now I get this weird error:
```
axxbxx@CCCP:/opt/AutoRclone-Rewrite-orig$ python3 autorclone.py --sync -s gcd-admin-rfid -sp 4KTV -d gcd-crypt -dp media/plex/4KTV --rclone-config-path /home/axxbxx/.config/rclone/rclone.conf --drive-chunk-size 64M --transfers 8 --dry-run
[2021-08-06 08:15:32] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-06 08:15:32] [AutoRClone] (untitled) [INFO] Generating RClone config file...
Traceback (most recent call last):
  File "/opt/AutoRclone-Rewrite-orig/autorclone.py", line 307, in <module>
    main()
  File "/opt/AutoRclone-Rewrite-orig/autorclone.py", line 88, in main
    end_id, src_is_crypt, dst_is_crypt = config_gen.gen_rclone_cfg(args, rclone_generated_config_path)
  File "/opt/AutoRclone-Rewrite-orig/util/config_gen.py", line 105, in gen_rclone_cfg
    source_remote, src_is_crypt = gen_remote_template(args.source, parsed_config, args, is_config_file_specified)
  File "/opt/AutoRclone-Rewrite-orig/util/config_gen.py", line 57, in gen_remote_template
    elif remote.source_path_id:
AttributeError: 'drive_remote' object has no attribute 'source_path_id'
```

New `rclone.conf` for reference, again, with secrets X'd out
```
cat /home/axxbxx/.config/rclone/rclone.conf
[gcd-team]
type = drive
client_id = xxxxxx.apps.googleusercontent.com
client_secret = xxxxxx
scope = drive
token = {xxxxxx}
team_drive = 0ALxxxxxxk9PVA
root_folder_id =

[gcd-crypt]
type = crypt
remote = gcd-team:media
password = xxxxxx
password2 = xxxxxx

[gcd-admin-rfid]
type = drive
client_id = xxxxxx.apps.googleusercontent.com
client_secret = xxxxxx
scope = drive
root_folder_id = 0xxxxxx5H3-0RxxxxxxHY2RxxxxxxTjQ
token = {xxxxxxx}
team_drive =

```

Also, the gcd-admin root_folder_id folder IS shared btw 👍

**Comment by williamjohnstone** [comment] 2021-08-06 13:59
Ah ok now you're running into issue #1 I will update that issue and work on it now

**Comment by williamjohnstone** [comment] 2021-08-06 14:08
Should be fixed now, update to the latest version and test again, I appreciate the detailed information too, please let me know if you run into any other issues.

**Comment by ghost** [comment] 2021-08-07 08:05
@endevrr 
Not sure what's going on, but here's the next error

```
axxbxx@CCCP:/opt/AutoRclone-Rewrite-orig$ python3 autorclone.py --sync -s gcd-admin-rfid -sp 4KTV -d gcd-crypt -dp media/plex/4KTV --rclone-config-path /home/axxbxx/.config/rclone/rclone2.conf --drive-chunk-size 64M --transfers 8 --dry-run
[2021-08-07 08:04:13] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-08-07 08:04:13] [AutoRClone] (untitled) [INFO] Generating RClone config file...
Traceback (most recent call last):
  File "/opt/AutoRclone-Rewrite-orig/autorclone.py", line 307, in <module>
    main()
  File "/opt/AutoRclone-Rewrite-orig/autorclone.py", line 88, in main
    end_id, src_is_crypt, dst_is_crypt = config_gen.gen_rclone_cfg(args, rclone_generated_config_path)
  File "/opt/AutoRclone-Rewrite-orig/util/config_gen.py", line 109, in gen_rclone_cfg
    dest_remote, dst_is_crypt = gen_remote_template(args.destination, parsed_config, args,is_config_file_specified)
  File "/opt/AutoRclone-Rewrite-orig/util/config_gen.py", line 40, in gen_remote_template
    remote_template += '[{}{:03d}_crypt]\n' \
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by williamjohnstone** [comment] 2021-08-07 13:26
Ok I'm going to open a separate issue for this

**Comment by williamjohnstone** [comment] 2021-08-07 13:34
Moving to #8
