### ISSUE TITLE
Encountered 3 successive errors when trying to contact rclone, switching accounts 

### ISSUE THREAD

**Issue by ghost** [endevrr/AutoRclone-Rewrite#4] opened 2021-07-13 22:59 UTC
AutoRclone-Rewrite-master python3 autorclone.py --copy -s 0AJzqsF092gQFUk9PVA -d 0AAhUBIpmAsKGUk9PVA --rclone-config-path /root/.config/rclone/rclone.conf
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] RClone detected: True
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] Generating RClone config file...
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] Starting job: untitled, at 17:49:15
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] Source: 0AJzqsF092gQFUk9PVA
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] Destination: 0AAhUBIpmAsKGUk9PVA
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] AutoRClone Log: logs/AutoRClone.log
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] RClone Log: logs/rclone.log
[2021-07-13 22:49:15] [AutoRClone] (untitled) [INFO] Calculating source size, please wait
[2021-07-13 22:51:42] [AutoRClone] (untitled) [INFO] Source size: 7.9TB
[2021-07-13 22:55:35] [AutoRClone] (untitled) [INFO] 0.0B/7.9TB @ 0.0B/s Files Checked: 1018 SA: 1 ETA: Calculating ETA...
[2021-07-13 22:55:52] [AutoRClone] (untitled) [INFO] Transfer limit reached or RClone is not transferring any data, switching service accounts
[2021-07-13 22:56:02] [AutoRClone] (untitled) [INFO] Encountered 3 successive errors when trying to contact rclone, switching accounts (1.0/3)
[2021-07-13 22:56:12] [AutoRClone] (untitled) [INFO] Encountered 3 successive errors when trying to contact rclone, switching accounts (2.0/3)
[2021-07-13 22:56:22] [AutoRClone] (untitled) [INFO] Job FINISHED (this message will be better soon)

i have 600 service accounts added to team drives...

**Comment by herodev1337** [comment] 2021-07-14 07:30
Why do you have 600 service accounts when you're only copying 8TB? 8TB use about 11 Accounts. Maybe you check your accounts and if they all work

**Comment by williamjohnstone** [comment] 2021-07-23 23:28
This is an issue I've experienced many times, I was under the impression that it was caused by the no bytes transferred check as when rclone is scanning files, see: `Files Checked: 1018` no bytes are transferred, but I pushed a fix for this, Please ensure you are on the latest version, and come back if you are still having issues.

Also note that this only occurs when rclone is exiting, so try running with rclone on its own and it may give you the error that is causing this. Could also be an implementation error on my part

**Comment by williamjohnstone** [comment] 2021-08-06 00:14
Should be fixed by #2

**Closed as completed by williamjohnstone** 2021-08-06 00:14 UTC
